name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # -------------------------
      # Setup Node
      # -------------------------

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      # -------------------------
      # Install Node dependencies
      # -------------------------

      - name: Install dependencies (authservice)
        run: npm ci
        working-directory: users/authservice

      - name: Install dependencies (userservice)
        run: npm ci
        working-directory: users/userservice

      - name: Install dependencies (webapp)
        run: npm ci
        working-directory: webapp

      - name: Install dependencies (game)
        run: npm ci
        working-directory: game

      - name: Install dependencies (gateway)
        run: npm ci
        working-directory: gateway

      # -------------------------
      # Setup Rust
      # -------------------------

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build gamey
        working-directory: gamey
        run: cargo build --release
