name: Release — Build & Deploy

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

env:
  IMAGE_TAG: ${{ github.event.release.tag_name }}

jobs:

  build-and-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - name: userservice
            path: users/userservice
          - name: authservice
            path: users/authservice
          - name: webapp
            path: webapp
          - name: gamey
            path: gamey
          - name: game
            path: game
          - name: gateway
            path: gateway

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish Docker Image
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: ${{ github.repository_owner }}/yovi_es4d/${{ matrix.service.name }}:${{ env.IMAGE_TAG }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          workdir: ${{ matrix.service.path }}

  deploy:
    name: Deploy on Server
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Deploy over SSH
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          user: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          command: |

            export IMAGE_TAG=${{ env.IMAGE_TAG }}

            echo "Logging into GHCR..."
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            echo "Downloading docker-compose.yml for release $IMAGE_TAG"
            wget https://raw.githubusercontent.com/${{ github.repository_owner }}/yovi_es4d/$IMAGE_TAG/docker-compose.yml -O docker-compose.yml

            echo "Stopping previous containers"
            docker compose down

            echo "Starting new containers"
            docker compose --profile dev up -d --pull always
