name: Release — Build & Deploy

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

env:
  IMAGE_TAG: ${{ github.event.release.tag_name }}

jobs:
  docker-push-webapp:
    name: Push webapp Docker Image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      env:
        API_URI: http://${{ secrets.DEPLOY_HOST }}:8000
        API_ORIGIN_URI: http://${{ secrets.DEPLOY_HOST }}:3000
      with:
          name: AndreaAcero/yovi_es4d/webapp
          username: ${{ github.actor }}
          password: ${{ secrets.ASW }}
          registry: ghcr.io
          workdir: webapp
          buildargs: |
            API_URI
            API_ORIGIN_URI
  docker-push-authservice:
    name: Push auth service Docker Image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
          name: AndreaAcero/yovi_es4d/authservice
          username: ${{ github.actor }}
          password: ${{ secrets.ASW }}
          registry: ghcr.io
          workdir: users/authservice
  docker-push-userservice:
      name: Push user service Docker Image to GitHub Packages
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
      steps:
      - uses: actions/checkout@v4
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: AndreaAcero/yovi_es4d/userservice
          username: ${{ github.actor }}
          password: ${{ secrets.ASW }}
          registry: ghcr.io
          workdir: users/userservice
  docker-push-gatewayservice:
    name: Push gateway service Docker Image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Update OpenAPI configuration
      run: |
        DEPLOY_HOST=${{ secrets.DEPLOY_HOST }}
        sed -i "s/SOMEIP/${DEPLOY_HOST}/g" gatewayservice/openapi.yaml
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      env:
        API_ORIGIN_URI: http://${{ secrets.DEPLOY_HOST }}:3000
      with:
        name: AndreaAcero/yovi_es4d/gatewayservice
        username: ${{ github.actor }}
        password: ${{ secrets.ASW }}
        registry: ghcr.io
        workdir: gatewayservice
        buildargs: API_ORIGIN_URI
  docker-push-game:
      name: Push game service Docker Image to GitHub Packages
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
      steps:
      - uses: actions/checkout@v4
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: AndreaAcero/yovi_es4d/game
          username: ${{ github.actor }}
          password: ${{ secrets.ASW }}
          registry: ghcr.io
          workdir: users/game
  docker-push-gamey:
      name: Push gamey service Docker Image to GitHub Packages
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
      steps:
      - uses: actions/checkout@v4
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: AndreaAcero/yovi_es4d/gamey
          username: ${{ github.actor }}
          password: ${{ secrets.ASW }}
          registry: ghcr.io
          workdir: users/gamey
  deploy:
    name: Deploy over SSH
    runs-on: ubuntu-latest
    needs: [docker-push-userservice,docker-push-authservice,docker-push-gatewayservice,docker-push-webapp,
          docker-push-gamey,docker-push-game]
    steps:
    - name: Deploy over SSH
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        user: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        command: |
          cp -r ./gatewayservice/monitoring /home/azureuser/gatewayservice/monitoring
          wget https://raw.githubusercontent.com/AndreaAcero/yovi_es4d/master/docker-compose.yml -O docker-compose.yml
          wget https://raw.githubusercontent.com/AndreaAcero/yovi_es4d/master/.env -O .env
          docker compose --profile prod down
          docker compose --profile prod up -d --pull always
